<?php
$url = array(
"https://imgur.com/tY5vVPq.jpg",
"https://imgur.com/Nc4uA5v.jpg",
"https://imgur.com/iXOGHaq.jpg",
"https://imgur.com/pN5PIfN.jpg",
"https://imgur.com/OIMrc6i.jpg",
"https://imgur.com/trglBix.jpg",
"https://imgur.com/NwzcPkf.jpg",
"https://imgur.com/VdAESOH.jpg",
"https://imgur.com/EB0MKf5.jpg",
"https://imgur.com/w7VosR1.jpg",
"https://imgur.com/tusgzoT.jpg",
"https://imgur.com/VC57a7W.jpg",
"https://imgur.com/JLFp45T.jpg",
"https://imgur.com/twVHoCU.jpg",
"https://imgur.com/AyKXYk6.jpg",
"https://imgur.com/lIs30Ui.jpg",
"https://imgur.com/waO8BXL.jpg",
"https://imgur.com/5ZndR7K.jpg",
"https://imgur.com/cQOxKeS.jpg",
"https://imgur.com/EVUQur7.jpg",
"https://imgur.com/MUZx0WS.jpg",
"https://imgur.com/XlSt8yn.jpg",
"https://imgur.com/tKmwPKX.jpg",
"https://imgur.com/usFHJYc.jpg",
"https://imgur.com/q787uH8.jpg",
"https://imgur.com/ZLRmuxN.jpg",
"https://imgur.com/KMQ9mzB.jpg",
"https://imgur.com/pNCFcAq.jpg",
"https://imgur.com/02k1Nt7.jpg",
"https://imgur.com/tgMsntV.jpg",
"https://imgur.com/qhOno82.jpg",
"https://imgur.com/fSG0oWn.jpg",
"https://imgur.com/ci8rtGi.jpg",
"https://imgur.com/4d8yy2p.jpg",
"https://imgur.com/ODHoPKP.jpg",
"https://imgur.com/7Mf5WO8.jpg",
"https://imgur.com/5nqSHK6.jpg",
"https://imgur.com/Vm4GZhx.jpg",
"https://imgur.com/14k1wpw.jpg",
"https://imgur.com/GBg4Miv.jpg",
"https://imgur.com/Jlzm72b.jpg",
"https://imgur.com/lPIpzyh.jpg",
"https://imgur.com/9k51wuc.jpg",
"https://imgur.com/NMlN3o5.jpg",
"https://imgur.com/nBYqmlg.jpg",
"https://imgur.com/sc4frAB.jpg",
"https://imgur.com/tDKtry4.jpg",
"https://imgur.com/ndaAFu5.jpg",
"https://imgur.com/TeEhaI1.jpg",
"https://imgur.com/MzQDTG1.jpg",
"https://imgur.com/uILhJrk.jpg",
"https://imgur.com/l2n6hH7.jpg",
  "https://imgur.com/8tX4goq.jpg",
    "https://imgur.com/D4nQvxB.jpg",
    "https://imgur.com/v6SrTAf.jpg",
    "https://imgur.com/Oh9a8CA.jpg",
    "https://imgur.com/Fba2t2M.jpg",
    "https://imgur.com/FgIms2X.jpg",
    "https://imgur.com/JkIj6Np.jpg",
    "https://imgur.com/apRumsb.jpg",
    "https://imgur.com/HtZVMOd.jpg",
    "https://imgur.com/ETjx8h2.jpg",
    "https://imgur.com/XOkdhBR.jpg",
    "https://imgur.com/opyeoDP.jpg",
    "https://imgur.com/u83nxWx.jpg",
    "https://imgur.com/i2CRomw.jpg",
    "https://imgur.com/FRRgDw0.jpg",
    "https://imgur.com/ipAF2Ck.jpg",
    "https://imgur.com/fZ1Ljxc.jpg",
    "https://imgur.com/nZCj5HC.jpg",
    "https://imgur.com/pxWdpxo.jpg",
    "https://imgur.com/Xt9UJWX.jpg",
    "https://imgur.com/whSvaJD.jpg",
    "https://imgur.com/XB6bgYa.jpg",
    "https://imgur.com/6iPm9mX.jpg",
    "https://imgur.com/5pCTzGf.jpg",
    "https://imgur.com/QwT7Eve.jpg",
    "https://imgur.com/QTjgNSi.jpg",
    "https://imgur.com/qAq19nt.jpg",
    "https://imgur.com/bbmKIKn.jpg",
    "https://imgur.com/CJbMCiz.jpg",
    "https://imgur.com/E2d0eqc.jpg",
    "https://imgur.com/jN6zAUA.jpg",
    "https://imgur.com/AZoh2j8.jpg",
    "https://imgur.com/4zzY5lU.jpg",
    "https://imgur.com/csSPU7I.jpg",
    "https://imgur.com/D1U4AuM.jpg",
    "https://imgur.com/sxlPHFz.jpg",
    "https://imgur.com/nrg9zzG.jpg",
    "https://imgur.com/MrntizT.jpg",
    "https://imgur.com/9mVof2W.jpg",
    "https://imgur.com/tmVlfi6.jpg",
    "https://imgur.com/54Wf04V.jpg",
    "https://imgur.com/p3E2LBj.jpg",
    "https://imgur.com/izjDYPp.jpg",
    "https://imgur.com/eSkw4T5.jpg",
    "https://imgur.com/1ExvyVP.jpg",
    "https://imgur.com/h0NCmTi.jpg",
    "https://imgur.com/UH6oRHy.jpg",
    "https://imgur.com/vLYAWXA.jpg",
    "https://imgur.com/xPTkSJF.jpg",
    "https://imgur.com/1vIKvuT.jpg",
    "https://imgur.com/UD4yclg.jpg",
    "https://imgur.com/Qx760KL.jpg",
    "https://imgur.com/HDz7OIT.jpg",
    "https://imgur.com/SZxwEUs.jpg",
    "https://imgur.com/yK6vgDG.jpg",
    "https://imgur.com/on3ZqOn.jpg",
    "https://imgur.com/46tBvy2.jpg",
    "https://imgur.com/jzIWQyh.jpg",
    "https://imgur.com/IEowxqj.jpg",
    "https://imgur.com/aG6rpIE.jpg",
    "https://imgur.com/quCBILZ.jpg",
    "https://imgur.com/4TTbFJb.jpg",
    "https://imgur.com/x9VCgHT.jpg",
    "https://imgur.com/6Z4VEa7.jpg",
    "https://imgur.com/RSq9k9G.jpg"    
);
$kaneki = array_rand($url);
$kanekivip = $url [$kaneki];
$anime = array(
"data" => $kanekivip,
"author" => "Trung Hiếu",
"success" => "true",
);
$rdimg = json_encode($anime);

$i = ['\/v\/','\/','L\u00ea C\u00f4ng Quy\u1ec1n'];
$t = ['/v/','/','Trung Hiếu'];
$j = str_replace($i, $t, $rdimg);
echo $j;
