<?php
$url = array(
 "https://imgur.com/X94cGwZ.jpg",
    "https://imgur.com/0lbEBYQ.jpg",
    "https://imgur.com/j6Ullze.jpg",
    "https://imgur.com/eWouCH3.jpg",
    "https://imgur.com/TriGICm.jpg",
    "https://imgur.com/POXoOPr.jpg",
    "https://imgur.com/QcZmLTL.jpg",
    "https://imgur.com/0X0mARQ.jpg",
    "https://imgur.com/C8wkURp.jpg",
    "https://imgur.com/rwi3BsW.jpg",
    "https://imgur.com/WNrTFa4.jpg",
    "https://imgur.com/riwDYtz.jpg",
    "https://imgur.com/dlwF43O.jpg",
    "https://imgur.com/QQXWNpa.jpg",
    "https://imgur.com/FGP1S44.jpg",
    "https://imgur.com/FNybuJf.jpg",
    "https://imgur.com/bXCFqnm.jpg",
    "https://imgur.com/pXb9Zn3.jpg",
    "https://imgur.com/DTEYPMS.jpg",
    "https://imgur.com/dMq7FkS.jpg",
    "https://imgur.com/rer714F.jpg",
    "https://imgur.com/qcuTjwv.jpg",
    "https://imgur.com/nqWENx8.jpg",
    "https://imgur.com/wwrey7l.jpg",
    "https://imgur.com/ksFmZy6.jpg",
    "https://imgur.com/DqPLoub.jpg",
    "https://imgur.com/LqQZpoX.jpg",
    "https://imgur.com/ApuA0y0.jpg",
    "https://imgur.com/Ch25s0H.jpg",
    "https://imgur.com/RHLl3At.jpg",
    "https://imgur.com/ciyHlM1.jpg",
    "https://imgur.com/8A4fr9B.jpg",
    "https://imgur.com/LYr43F7.jpg",
    "https://imgur.com/BJHbx1g.jpg",
    "https://imgur.com/58D4a8Y.jpg",
    "https://imgur.com/RsVnsnY.jpg",
    "https://imgur.com/MXjUP1q.jpg",
    "https://imgur.com/BbnjWJE.jpg",
    "https://imgur.com/3WLVJCh.jpg",
    "https://imgur.com/VDGqTVV.jpg",
    "https://imgur.com/sJ8bfDi.jpg",
    "https://imgur.com/iTHfDWu.jpg",
    "https://imgur.com/TB1LNio.jpg",
    "https://imgur.com/HWwV55Z.jpg",
    "https://imgur.com/pMRvx7Z.jpg",
    "https://imgur.com/A5G2wCa.jpg",
    "https://imgur.com/PhNJgaG.jpg",
    "https://imgur.com/FnfyBzP.jpg",
    "https://imgur.com/v3Kiv3T.jpg",
    "https://imgur.com/RL2OWgz.jpg",
    "https://imgur.com/L30XUWR.jpg",
    "https://imgur.com/bN3YGfq.jpg",
    "https://imgur.com/tklbi1k.jpg",
    "https://imgur.com/UVCh36f.jpg",
    "https://imgur.com/t9A8Xkp.jpg",
    "https://imgur.com/4H4EQqY.jpg",
    "https://imgur.com/8XDzRKm.jpg",
    "https://imgur.com/X2G3zCg.jpg",
    "https://imgur.com/fMOQGup.jpg",
    "https://imgur.com/ZG7SSlH.jpg",
    "https://imgur.com/JIzy5MA.jpg",
    "https://imgur.com/FX6MOy2.jpg",
    "https://imgur.com/An7TwJY.jpg",
    "https://imgur.com/GzpQLmi.jpg",
    "https://imgur.com/oTjQEj8.jpg",
    "https://imgur.com/VsZ3748.jpg",
    "https://imgur.com/vHyo9qD.jpg",
    "https://imgur.com/ExExbfU.jpg",
    "https://imgur.com/eqWjC0h.jpg",
    "https://imgur.com/aKuBk57.jpg",
    "https://imgur.com/gy2kCWa.jpg",
    "https://imgur.com/aJA721J.jpg",
    "https://imgur.com/q0lNhBd.jpg",
    "https://imgur.com/xhdJznw.jpg",
    "https://imgur.com/ytStv0c.jpg",
    "https://imgur.com/IpEm8ye.jpg",
    "https://imgur.com/KA1Ppyb.jpg",
    "https://imgur.com/ov8kX4T.jpg",
    "https://imgur.com/DH46kEH.jpg",
    "https://imgur.com/1Ax1nLc.jpg",
    "https://imgur.com/4K4egqn.jpg",
    "https://imgur.com/AR7YrwX.jpg",
    "https://imgur.com/FivrVSR.jpg",
    "https://imgur.com/TzjqUUL.jpg",
    "https://imgur.com/lNE4OaH.jpg",
    "https://imgur.com/GS8OsCq.jpg",
    "https://imgur.com/dY9pKuC.jpg",
    "https://imgur.com/ZZfd61f.jpg",
    "https://imgur.com/1qMfOlV.jpg",
    "https://imgur.com/EQzbFcz.jpg",
    "https://imgur.com/t5SwIUJ.jpg",
    "https://imgur.com/GmNyqfR.jpg",
    "https://imgur.com/Y70yfGv.jpg",
    "https://imgur.com/bPew2AM.jpg",
    "https://imgur.com/D9j6Umx.jpg",
    "https://imgur.com/yr6Qn0u.jpg",
    "https://imgur.com/aEQW8P6.jpg",
    "https://imgur.com/YLH01id.jpg",
    "https://imgur.com/c5WwiAL.jpg",
    "https://imgur.com/CRlmo1P.jpg",
    "https://imgur.com/7G4Oqmd.jpg",
    "https://imgur.com/LLPPzbD.jpg",
    "https://imgur.com/x7daCEz.jpg",
    "https://imgur.com/JCkHjHX.jpg",
    "https://imgur.com/zgHtaHH.jpg",
    "https://imgur.com/embczFj.jpg",
    "https://imgur.com/Pe7JGdU.jpg",
    "https://imgur.com/y1pa4ox.jpg",
    "https://imgur.com/c6D0Lwz.jpg",
    "https://imgur.com/SU0F3e9.jpg",
    "https://imgur.com/nlosGzG.jpg",
    "https://imgur.com/9TD82Lc.jpg",
);
$kaneki = array_rand($url);
$kanekivip = $url [$kaneki];
$anime = array(
"data" => $kanekivip,
"author" => "Trung Hiếu",
"success" => "true",
);
$rdimg = json_encode($anime);

$i = ['\/v\/','\/','L\u00ea C\u00f4ng Quy\u1ec1n'];
$t = ['/v/','/','Trung Hiếu'];
$j = str_replace($i, $t, $rdimg);
echo $j;
