<?php
$url = array(
"https://i.imgur.com/GI4x41d.mp4",
"https://i.imgur.com/wb46oYQ.mp4",
"https://i.imgur.com/1foNZZM.mp4",
"https://i.imgur.com/R9N7YCd.mp4",
"https://i.imgur.com/lsNhYMJ.mp4",
"https://i.imgur.com/yFrCWKY.mp4",
"https://i.imgur.com/cl2pRZf.mp4",
"https://i.imgur.com/Pbd7rVW.mp4",
"https://i.imgur.com/RNtgDlt.mp4",
"https://i.imgur.com/NJJkJ0e.mp4",
"https://i.imgur.com/8gRU2rG.mp4",
"https://i.imgur.com/mlAPSQj.mp4",
"https://i.imgur.com/VnE3SBz.mp4",
"https://i.imgur.com/pwtMWYI.mp4",
"https://i.imgur.com/k23iANS.mp4",
"https://i.imgur.com/vqRyNCV.mp4",
"https://i.imgur.com/ZmyPBBF.mp4",
"https://i.imgur.com/CCXaXpn.mp4",
"https://i.imgur.com/8ZvTo7C.mp4",
"https://i.imgur.com/h8l4GZI.mp4",
"https://i.imgur.com/t14plaB.mp4",
"https://i.imgur.com/1DLM4aU.mp4",
"https://i.imgur.com/FthL5gn.mp4",
"https://i.imgur.com/msalS8t.mp4",
"https://i.imgur.com/T5XpsU9.mp4",
  "https://i.imgur.com/wxZvkQG.mp4",
  "https://i.imgur.com/EDZ4qg5.mp4",
  "https://i.imgur.com/haxhpmz.mp4",
  "https://i.imgur.com/8Wrl3mS.mp4",
  "https://i.imgur.com/Zwr06lD.mp4",
  "https://i.imgur.com/bV9UMkm.mp4",
  "https://i.imgur.com/g2A0NbR.mp4",
  "https://i.imgur.com/h1P5TNP.mp4",
  "https://i.imgur.com/a0vy0Es.mp4",
  "https://i.imgur.com/KBXNFot.mp4",
  "https://i.imgur.com/dCXTPvv.mp4",
  "https://i.imgur.com/W7tiRYa.mp4",
  "https://i.imgur.com/jwFIJed.mp4",
  "https://i.imgur.com/gpqUJkJ.mp4",
  "https://i.imgur.com/1LDqC3Q.mp4",
  "https://i.imgur.com/c7g6q22.mp4",
  "https://i.imgur.com/nYjixly.mp4",
  "https://i.imgur.com/cRxj0AN.mp4",
  "https://i.imgur.com/y2mFbfq.mp4",
  "https://i.imgur.com/yPJPv4q.mp4",
  "https://i.imgur.com/WjVfowo.mp4",
  "https://i.imgur.com/zrXPSrr.mp4",
  "https://i.imgur.com/a7TEDRg.mp4",
  "https://i.imgur.com/GoWRsbs.mp4",
  "https://i.imgur.com/rXpxjRa.mp4",
  "https://i.imgur.com/4Y7gK9i.mp4",
  "https://i.imgur.com/4MzJAbm.mp4",
  "https://i.imgur.com/Ff0C8tf.mp4",
  "https://i.imgur.com/EXAf0wt.mp4",
  "https://i.imgur.com/H3t7YUV.mp4",
  "https://i.imgur.com/sPi2RHJ.mp4",
  "https://i.imgur.com/Yd3BOZr.mp4",
  "https://i.imgur.com/k7dWZLk.mp4",
  "https://i.imgur.com/3UEW4Eq.mp4",
  "https://i.imgur.com/ava5Utg.mp4",
  "https://i.imgur.com/knkStTE.mp4",
  "https://i.imgur.com/kv6B97I.mp4",
  "https://i.imgur.com/LlIji4C.mp4",
  "https://i.imgur.com/HQaDwg0.mp4",
  "https://i.imgur.com/5vzomnU.mp4",
  "https://i.imgur.com/5BGsgYw.mp4",
  "https://i.imgur.com/5cl8mYW.mp4",
  "https://i.imgur.com/pkSzgHG.mp4",
  "https://i.imgur.com/8fwXHg5.mp4",
  "https://i.imgur.com/dzuBaia.mp4",
  "https://i.imgur.com/CEALr4l.mp4",
  "https://i.imgur.com/7Dvm4g7.mp4",
  "https://i.imgur.com/hhV9keY.mp4",
  "https://i.imgur.com/4UEWszw.mp4",
  "https://i.imgur.com/UjPz94q.mp4",
  "https://i.imgur.com/ERyqDST.mp4",
  "https://i.imgur.com/Qy7kmIU.mp4",
  "https://i.imgur.com/5vsLdkw.mp4",
  "https://i.imgur.com/tUDUEtc.mp4",
  "https://i.imgur.com/2cIbhP3.mp4",
  "https://i.imgur.com/swqikQN.mp4",
  "https://i.imgur.com/XUtldkn.mp4",
 "https://i.imgur.com/dmz3csF.mp4",
  "https://i.imgur.com/LODPRSg.mp4",
  "https://i.imgur.com/z88hoDp.mp4",
  "https://i.imgur.com/br7xCek.mp4",
  "https://i.imgur.com/zg84Cyp.mp4",
  "https://i.imgur.com/0z8ppON.mp4",
  "https://i.imgur.com/sP21V31.mp4",
  "https://i.imgur.com/szI1tlX.mp4",
  "https://i.imgur.com/hihJmJC.mp4",
  "https://i.imgur.com/5orFI43.mp4",
  "https://i.imgur.com/BbHnJML.mp4",
  "https://i.imgur.com/oZUcIih.mp4",
);
$kaneki = array_rand($url);
$kanekivip = $url [$kaneki];
$anime = array(
"data" => $kanekivip,
"author" => "Trung Hiếu",
"success" => "true",
);
$rdimg = json_encode($anime);

$i = ['\/v\/','\/','L\u00ea C\u00f4ng Quy\u1ec1n'];
$t = ['/v/','/','Trung Hiếu'];
$j = str_replace($i, $t, $rdimg);
echo $j;
